# Generated by Django 4.1.13 on 2026-03-19 02:43

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='NguoiDung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('ma_danh_muc', models.AutoField(primary_key=True, serialize=False)),
                ('ten_danh_muc', models.CharField(max_length=100, unique=True)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Danh mục',
                'verbose_name_plural': 'Danh mục',
            },
        ),
        migrations.CreateModel(
            name='DiaDiem',
            fields=[
                ('ma_dia_diem', models.AutoField(primary_key=True, serialize=False)),
                ('ten_dia_diem', models.CharField(max_length=200)),
                ('mo_ta', models.TextField()),
                ('dia_chi', models.CharField(max_length=255)),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='dia_diem/')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ma_danh_muc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dia_diem_list', to='app.danhmuc')),
            ],
            options={
                'verbose_name': 'Địa điểm',
                'verbose_name_plural': 'Địa điểm',
            },
        ),
        migrations.CreateModel(
            name='TourDuLich',
            fields=[
                ('ma_tour', models.AutoField(primary_key=True, serialize=False)),
                ('ten_tour', models.CharField(max_length=200)),
                ('thoi_gian', models.IntegerField(help_text='Số ngày')),
                ('gia', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ma_dia_diem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_list', to='app.diadiem')),
            ],
            options={
                'verbose_name': 'Tour du lịch',
                'verbose_name_plural': 'Tour du lịch',
            },
        ),
        migrations.CreateModel(
            name='DatCho',
            fields=[
                ('ma_dat_cho', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('trang_thai', models.CharField(choices=[('pending', 'Đang chờ'), ('confirmed', 'Đã xác nhận'), ('cancelled', 'Đã hủy')], default='pending', max_length=20)),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dat_cho_list', to=settings.AUTH_USER_MODEL)),
                ('ma_tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dat_cho_list', to='app.tourdulich')),
            ],
        ),
        migrations.CreateModel(
            name='DanhGia',
            fields=[
                ('ma_danh_gia', models.AutoField(primary_key=True, serialize=False)),
                ('so_sao', models.IntegerField(choices=[(1, '1 sao'), (2, '2 sao'), (3, '3 sao'), (4, '4 sao'), (5, '5 sao')])),
                ('noi_dung_binh_luan', models.TextField()),
                ('ngay_danh_gia', models.DateTimeField(auto_now_add=True)),
                ('ma_dia_diem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='app.diadiem')),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-ngay_danh_gia'],
                'unique_together': {('ma_nguoi_dung', 'ma_dia_diem')},
            },
        ),
    ]
