# Generated by Django 5.2.10 on 2026-03-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_datcho_ngay_dat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourdulich',
            name='ma_dia_diem',
        ),
        migrations.AddField(
            model_name='tourdulich',
            name='ma_dia_diem',
            field=models.ManyToManyField(related_name='tour_list', to='app.diadiem'),
        ),
    ]
