# Generated by Django 5.2.10 on 2026-04-27 14:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_tourdulich_ma_dia_diem_tourdulich_ma_dia_diem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdulich',
            name='anh_dai_dien',
            field=models.ImageField(blank=True, null=True, upload_to='tour/'),
        ),
        migrations.AddField(
            model_name='tourdulich',
            name='ngay_tao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
