# Generated by Django 5.2.10 on 2026-04-27 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tourdulich_anh_dai_dien_tourdulich_ngay_tao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tourdulich',
            name='anh_dai_dien',
        ),
        migrations.RemoveField(
            model_name='tourdulich',
            name='ngay_tao',
        ),
        migrations.CreateModel(
            name='RequestDiaDiem',
            fields=[
                ('ma_request', models.AutoField(primary_key=True, serialize=False)),
                ('ten_dia_diem', models.CharField(max_length=200)),
                ('mo_ta', models.TextField()),
                ('dia_chi', models.CharField(max_length=255)),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='request_dia_diem/')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('pending', 'Đang chờ'), ('approved', 'Đã chấp nhận'), ('rejected', 'Đã từ chối')], default='pending', max_length=20)),
                ('ly_do_tu_choi', models.TextField(blank=True, null=True)),
                ('ma_danh_muc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.danhmuc')),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_list', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu tạo địa điểm',
                'verbose_name_plural': 'Yêu cầu tạo địa điểm',
            },
        ),
    ]
