# Generated by Django 5.2.10 on 2026-04-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_tourdulich_anh_dai_dien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourdulich',
            name='so_luong_cho',
            field=models.PositiveIntegerField(default=10, help_text='Số lượng chỗ tối đa'),
        ),
    ]
