# Generated by Django 4.1.13 on 2026-04-30 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_tourdulich_so_luong_cho'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='diadiem',
            options={'permissions': [('view_report', 'Can access report page')], 'verbose_name': 'Địa điểm', 'verbose_name_plural': 'Địa điểm'},
        ),
        migrations.AddField(
            model_name='diadiem',
            name='ma_nguoi_dung',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dia_diem_created', to=settings.AUTH_USER_MODEL),
        ),
    ]
