# Generated by Django 4.1.13 on 2026-04-30 12:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_diadiem_options_diadiem_ma_nguoi_dung'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestReportPermission',
            fields=[
                ('ma_request', models.AutoField(primary_key=True, serialize=False)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('trang_thai', models.CharField(choices=[('pending', 'Đang chờ'), ('approved', 'Đã chấp nhận'), ('rejected', 'Đã từ chối')], default='pending', max_length=20)),
                ('ly_do_tu_choi', models.TextField(blank=True, null=True)),
                ('ma_nguoi_dung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_permission_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Yêu cầu cấp quyền báo cáo',
                'verbose_name_plural': 'Yêu cầu cấp quyền báo cáo',
            },
        ),
    ]
